# - !ScreenConfig
#   location: [0,0]
#   view_module: time_view
#   config:
#     time_part: hour

# - !ScreenConfig
#   location: [1,0]
#   view_module: time_view
#   config:
#     time_part: minute


- !ScreenConfig
  location: [0,0]
  view_modules: 
    - !ModuleConfig
      name: fade_in_view
      onetime: true
      duration_sec: 15
      config:
        color: [242, 80, 34]
    - !ModuleConfig
      name: clock_view
      config: "None"

- !ScreenConfig
  location: [1,0]
  view_modules: 
    - !ModuleConfig
      name: fade_in_view
      onetime: true
      duration_sec: 15
      config:
        color: [127, 186, 0]
    - !ModuleConfig
      name: weather_view
      config:
        refresh_interval_seconds: 5

- !ScreenConfig
  location: [0,1]
  view_modules: 
    - !ModuleConfig
      name: fade_in_view
      onetime: true
      duration_sec: 15
      config:
        color: [0, 164, 239]
    - !ModuleConfig
      name: chart_view
      config:
        refresh_interval_seconds: 5

- !ScreenConfig
  location: [1,1]
  view_modules: 
    - !ModuleConfig
      name: fade_in_view
      onetime: true
      duration_sec: 15
      config:
        color: [255, 185, 0]
    - !ModuleConfig
      name: chart_view
      config:
        refresh_interval_seconds: 5